// Generated by gencpp from file learning_commuication/AddTwoInts.msg
// DO NOT EDIT!


#ifndef LEARNING_COMMUICATION_MESSAGE_ADDTWOINTS_H
#define LEARNING_COMMUICATION_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <learning_commuication/AddTwoIntsRequest.h>
#include <learning_commuication/AddTwoIntsResponse.h>


namespace learning_commuication
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace learning_commuication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_commuication::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::learning_commuication::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::learning_commuication::AddTwoInts > {
  static const char* value()
  {
    return "learning_commuication/AddTwoInts";
  }

  static const char* value(const ::learning_commuication::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::learning_commuication::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::learning_commuication::AddTwoInts > 
template<>
struct MD5Sum< ::learning_commuication::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_commuication::AddTwoInts >::value();
  }
  static const char* value(const ::learning_commuication::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_commuication::AddTwoIntsRequest> should match 
// service_traits::DataType< ::learning_commuication::AddTwoInts > 
template<>
struct DataType< ::learning_commuication::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::learning_commuication::AddTwoInts >::value();
  }
  static const char* value(const ::learning_commuication::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_commuication::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::learning_commuication::AddTwoInts > 
template<>
struct MD5Sum< ::learning_commuication::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_commuication::AddTwoInts >::value();
  }
  static const char* value(const ::learning_commuication::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_commuication::AddTwoIntsResponse> should match 
// service_traits::DataType< ::learning_commuication::AddTwoInts > 
template<>
struct DataType< ::learning_commuication::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::learning_commuication::AddTwoInts >::value();
  }
  static const char* value(const ::learning_commuication::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_COMMUICATION_MESSAGE_ADDTWOINTS_H
