% Script file: QFTSTRT2
% The purpose of this script is to setup the information window and
% locations of windows for the demonstration format
% Copyright (c) 1995-98 by The MathWorks, Inc.
%       $Revision: 1.6 $

% setup locations and sizes of display windows no matter what the size
% of the monitor
%=================================
any_scr=1 ./[640,480,640,480];
win1_loc=[7,194,320,240].*any_scr;
win2_loc=[136,102,320,240].*any_scr;
win3_loc=[312,7,320,240].*any_scr;
win4_loc=[312,194,320,240].*any_scr;

% setup the information window
%=================================
fig_color=[128/255,128/255,128/255];
info_scr = 1 ./[390,90,390,90];

info_win = colordef('new','none');
set(info_win,'name',fig_str,'numbertitle','off','menubar','none',...
             'units','norm','color',fig_color,'pos',[10,10,390,90].*any_scr,...
             'vis','off','tag','info_win',...
             'closerequestfcn','close(findobj(''tag'',''qft''),''force'');close(findobj(allchild(0),''tag'',''info_win''),''force'');clear global',...
             'handlevisibility','callback');
info_str(1)=uicontrol(info_win,'style','text','units','norm','pos',[5,60,390,20].*info_scr,...
                   'background',fig_color,'foreground',[1,1,1],...
                   'horizontalalignment','left');
info_str(2)=uicontrol(info_win,'style','text','units','norm','pos',[5,35,390,20].*info_scr,...
                   'background',fig_color,'foreground',[1,1,1],...
                   'horizontalalignment','left');
info_btn(1)=uicontrol(info_win,'style','push','units','norm','pos',[263,5,113,20].*info_scr,...
       'string','Quit','callback',...
       'close(findobj(''tag'',''qft''),''force'');close(findobj(''tag'',''info_win''),''force'');close(findobj(''tag'',''CAD window''),''force'');clear global',...
       'tag','QuitButton',...
       'enable','off');
info_btn(2)=uicontrol(info_win,'style','push','units','norm','pos',[138,5,113,20].*info_scr,...
       'string','Info','enable','off');
info_btn(3)=uicontrol(info_win,'style','push','units','norm','pos',[13,5,113,20].*info_scr,...
                      'string','Continue...','enable','off');
drawnow;
